apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/rollouts.io_rollouts.yaml
  - bases/rollouts.io_analysistemplates.yaml
  - bases/rollouts.io_clusteranalysistemplates.yaml
  - bases/rollouts.io_analysisruns.yaml
  - bases/rollouts.io_experiments.yaml
